# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Project Links
    url: '#links'
    weight: 10
  - name: Database
    url: 'database/'
    weight: 15
  - name: Data Policy
    url: 'policy/'
    weight: 16
# - name: AusTraits R Package
#    url: 'https://github.com/traitecoevo/austraits'
#    weight: 17
  - name: Team
    url: '#team'
    weight: 20
  - name: Contributors
    url: 'contributors/'
    weight: 40
  - name: Partners
    url: '#partners'
    weight: 30
#  - name: Publications
#    url: '#publications'
#    weight: 50
  - name: Contact
    url: '#contact'
    weight: 70
