project:
  type: website

website:
  title: "AusTraits"
  
  navbar:
    left:
      - href: index.html#access-and-usage
        text: Access and Usage
      - href: index.html#structure
        text: Structure
      - href: index.html#software-and-outputs
        text: Software and Outputs
      - href: index.html#ongoing-efforts
        text: Ongoing Efforts
      - href: impact.qmd
        text: Our Impact
      - href: team/team-partners.qmd
        text: Our Team
      - href: contributors.qmd
        text: Data Contributors
      - href: contact.qmd
        text: Contact Us
    right:  
      - href: https://github.com/traitecoevo/austraits.org
        icon: github

  search: 
    location: navbar


format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: source

execute:
  freeze: auto
